programs:
  - name: first
    path: target/x86_64-unknown-linux-musl/debug/harness
    args:
      - -o
      - system-tests/child-dump/first.yml
    uid: 0
    gid: 0

  - name: second
    path: target/x86_64-unknown-linux-musl/debug/harness
    args:
      - -o
      - system-tests/child-dump/second.yml
    after:
      - first
      - fourth
    uid: 1000
    gid: 100

  - name: third
    path: target/x86_64-unknown-linux-musl/debug/harness
    args:
      - -o
      - system-tests/child-dump/third.yml
    after:
      - first
      - second
    uid: 1000
    gid: 100

  - name: fourth
    path: target/x86_64-unknown-linux-musl/debug/harness
    args:
      - -o
      - system-tests/child-dump/fourth.yml
    after:
      - first
      - third
    uid: 1000
    gid: 100
