---

image: docker:latest
services:
  - docker:dind

stages:
  - build-debug
  - build-release

build-debug:
  stage: build-debug
  script:
    - scripts/local/build
  artifacts:
    paths:
      - target/path/cinit

build-release:
  stage: build-release
  script:
    - export BUILD_FLAGS="--release"
    - scripts/local/build
  artifacts:
    paths:
      - target/path/cinit
  only:
    - tags

