#  cinit: process initialisation program for containers
#  Copyright (C) 2019 The cinit developers
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

---

services:
  - docker:dind

stages:
  - build
  - build-release

system-test:
  stage: build
  image: docker:latest
  script:
    - scripts/local/build
  artifacts:
    paths:
      - target/path/cinit
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - target
      - .cargo

build-release:
  stage: build-release
  image: docker:latest
  script:
    - export BUILD_FLAGS="--release"
    - scripts/local/build
  artifacts:
    paths:
      - target/path/cinit
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - target
      - .cargo
  only:
    - tags

build:
  stage: build
  image: rust:latest
  script:
    - apt-get update
    - apt-get -y --no-install-recommends install libsystemd-dev
    - cargo build
  cache:
    key: ${CI_JOB_NAME}
    policy: pull
    paths:
      - target
      - .cargo

format:
  stage: build
  image: rust:latest
  script:
    - apt-get update
    - apt-get -y --no-install-recommends install libsystemd-dev
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  cache:
    key: ${CI_JOB_NAME}
    policy: pull
    paths:
      - target
      - .cargo

audit:
  stage: build
  image: rust:latest
  script:
    - apt-get update
    - apt-get -y --no-install-recommends install libsystemd-dev
    - cargo install cargo-audit
    - cargo audit
  cache:
    key: ${CI_JOB_NAME}
    policy: pull
    paths:
      - target
      - .cargo

clippy:
  stage: build
  image: rust:latest
  script:
    - apt-get update
    - apt-get -y --no-install-recommends install libsystemd-dev
    - rustup component add clippy
    - cargo clippy --release -j 8 -- -D clippy::all
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - target
      - .cargo

test:
  stage: build
  image: rust:latest
  script:
    - apt-get update
    - apt-get -y --no-install-recommends install libsystemd-dev
    - ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime
    - cargo test
  cache:
    key: ${CI_JOB_NAME}
    paths:
      - target
      - .cargo
