[package]
name = "cinit"
version = "1.2.0"
authors = ["Maximilian Falkenstein <uubk@users.noreply.github.com>",
           "Jan Veen <jan.veen@posteo.de>"]
description = "Init program for UNIX processes"
license-file = "LICENSE"
build = "build.rs"
edition = "2018"

[profile.release]
lto = true

[dependencies]
clap = "2.27.0"
log = "0.4"
serde = "1.0.80"
serde_derive = "1.0"
serde_yaml = "0.8.7"
nix = "0.12.0"
libc = "0.2.43"
capabilities = "0.3.0"
petgraph = "0.4.13"
tera = "0.11.20"
time = "0.1.40"

[dependencies.log4rs]
version = "0.8.1"
default-features = false
features = ["file", "pattern_encoder", "console_appender"]
