[package]
name = "cinit"
version = "1.5.2"
authors = ["Maximilian Falkenstein <uubk@users.noreply.github.com>",
           "Jan Veen <jan.veen@posteo.de>",
           "Ben Fiedler <ben@sjfiedler.de>"]
description = "Init program for UNIX processes"
license = "GPL-3.0-or-later"
build = "build.rs"
edition = "2018"

[profile.release]
lto = true

[dependencies]
clap = "2.33.3"
log = "0.4.11"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_yaml = "0.8.13"
nix = "0.19.0"
libc = "0.2.79"
capabilities = "0.3.0"
petgraph = "0.5.1"
tera = "1.5.0"
chrono = "0.4.19"

[dependencies.log4rs]
version = "0.13.0"
default-features = false
features = ["file", "pattern_encoder", "console_appender"]

[build-dependencies]
vergen = "3"
