#  cinit: process initialisation program for containers
#  Copyright (C) 2019 The cinit developers
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

programs:
  - name: first
    path: target/path/harness
    type: notify
    user: testuser
    group: testgroup
    before:
      - second
    args:
      - -o
      - system-tests/child-dump/first.yml
      - -n
      - -s
      - 1

  - name: second
    path: target/path/harness
    args:
      - -o
      - system-tests/child-dump/second.yml
    user: testuser
    group: testgroup

  - name: harness
    path: target/path/harness
    type: notify
    args:
      - -o
      - system-tests/child-dump/harness.yml
    user: testuser
    group: testgroup

  - name: status-publisher
    path: target/path/harness
    type: notify
    args:
      - -S
      - test status
      - -n
      - -s
      - 1
      - -o
      - system-tests/child-dump/status-publisher.yml
    user: testuser
    group: testgroup
