programs:
  - name: some-caps
    path: target/x86_64-unknown-linux-musl/debug/harness
    args:
      - -o
      - system-tests/child-dump/some-caps.yml
    uid: 1000
    gid: 100
    pty: true
    capabilities:
      - CAP_KILL
      - CAP_NET_RAW

  - name: no-caps
    path: target/x86_64-unknown-linux-musl/debug/harness
    args:
      - -o
      - system-tests/child-dump/no-caps.yml
    uid: 1000
    gid: 100
    pty: true
