#  cinit: process initialisation program for containers
#  Copyright (C) 2019 The cinit developers
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

programs:
  - name: some-caps
    path: target/path/harness
    args:
      - -o
      - system-tests/child-dump/some-caps.yml
    uid: 1409
    gid: 1409
    capabilities:
      - CAP_KILL
      - CAP_NET_RAW

  - name: root-gets-all-caps
    path: target/path/harness
    args:
      - -o
      - system-tests/child-dump/root-gets-all-caps.yml
    capabilities:
      - CAP_KILL
      - CAP_NET_RAW

  - name: no-caps
    path: target/path/harness
    args:
      - -o
      - system-tests/child-dump/no-caps.yml
    uid: 1409
    gid: 1409
