programs:
  - name: first
    path: target/path/harness
    args:
      - -o
      - system-tests/child-dump/first.yml
      - -r
      - 42

  - name: second
    path: target/path/harness
    uid: 1409
    gid: 1409
    args:
      - -o
      - system-tests/child-dump/second.yml
    after:
      - first
