#!/bin/sh

#  cinit: process initialisation program for containers
#  Copyright (C) 2019 The cinit developers
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -ex

PROJECT_ROOT="$( cd "$( dirname "$(readlink -f $0)" )" && pwd )/../.."

DOCKER_NAME=cinit
DOCKER_TAG="$DOCKER_NAME:build"
DOCKER_PROJECT_ROOT=/usr/src/cinit

mkdir -p "$PROJECT_ROOT/target/registry/"

docker pull docker.io/rust:bullseye

docker build -t $DOCKER_TAG .

# Build servers don't have a TTY
if [ -t 1 ] ; then
    TTY=--tty
fi

# Only outside gitlab for capability tests
if [ "$CI_JOB_NAME" = "" ] ; then
    PRIVILEGED=--privileged
fi

ALTERNATES=$(cat $PROJECT_ROOT/.git/objects/info/alternates || true)
if [ ! -z $ALTERNATES ] ; then
    ALTERNATES="--volume $ALTERNATES:$ALTERNATES"
fi

docker run --rm                                                             \
        $TTY                                                                \
        --interactive                                                       \
        $PRIVILEGED                                                         \
        --volume "$PROJECT_ROOT/:$DOCKER_PROJECT_ROOT"                      \
        --volume "$PROJECT_ROOT/target/registry/:/usr/local/cargo/registry" \
        $ALTERNATES                                                         \
        --workdir "$DOCKER_PROJECT_ROOT"                                    \
        --env BUILD_FLAGS="$BUILD_FLAGS"                                    \
        $DOCKER_TAG                                                         \
        $DOCKER_PROJECT_ROOT/scripts/container/test
