programs:
  - name: first
    path: target/x86_64-unknown-linux-musl/debug/harness
    args:
      - -o
      - system-tests/child-dump/first.yml
    env:
      - FOO: bar
      - BAR: "{{ TERM }}-{{ FOO }}"