#!/bin/bash

export PROJECT_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."

export UUT="$PROJECT_ROOT/target/x86_64-unknown-linux-musl/debug/cinit"

if [[ "$1" == "-v" ]] ; then
    export VERBOSE=1
else
    export VERBOSE=0
fi

if [[ ! -f "$UUT" ]] ; then
    echo "cinit not found"
    exit 1
fi

rm -rf child-dump
mkdir child-dump

python3 -m unittest discover -s "$PROJECT_ROOT"/system-tests -p '__init__.py'

