#!/bin/bash

#  cinit: process initialisation program for containers
#  Copyright (C) 2019 The cinit developers
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

cd /usr/src

git clone                                                                   \
        --branch libcap-2.28                                                \
        --depth 1                                                           \
        https://git.kernel.org/pub/scm/libs/libcap/libcap.git               \
        libcap

cd libcap

CFLAGS="-D_FORTIFY_SOURCE=0 -O2 -pipe -fstack-protector-strong -fno-plt -march=x86-64 -mtune=generic"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"

sed -i "s/CFLAGS :=/CFLAGS += $CFLAGS/" Make.Rules
sed -i "s/LDFLAGS :=/LDFLAGS += $LDFLAGS/" Make.Rules

make

make prefix=/ lib=/usr/lib/ RAISE_SETFCAP=no install

cd ..
rm -rf libcap
