#!/bin/bash

set -e

U=$(getent passwd $USER_ID | tr ':' ' ' | awk '{ print $1 }')

export BUILD_FLAGS

export TARGET="--target=x86_64-unknown-linux-musl"

su $U -c "cargo build $BUILD_FLAGS $TARGET -j 8"
su $U -c "cargo clippy $BUILD_FLAGS $TARGET -j 8 -- -D clippy::all"
su $U -c "RUST_BACKTRACE=1 cargo test -j 1 $TARGET"
su $U -c "cargo doc"


GREEN='\033[1;32m'
NC='\033[0m'

echo
echo -e "    ${GREEN}Running system tests${NC}"

rm -rf target/path
if echo $BUILD_FLAGS | grep 'release' >/dev/null ; then
    ln -s "x86_64-unknown-linux-musl/release/" target/path
else
    ln -s "x86_64-unknown-linux-musl/debug/" target/path
fi
chown -h "$USER_ID":"$GROUP_ID" target/path

system-tests/test

