#!/bin/sh

#  cinit: process initialisation program for containers
#  Copyright (C) 2019 The cinit developers
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.

set -e

U=$(getent passwd $USER_ID | tr ':' ' ' | awk '{ print $1 }')

export BUILD_FLAGS

export TARGET="--target=x86_64-unknown-linux-musl"

su $U -c "/usr/local/cargo/bin/cargo build $BUILD_FLAGS $TARGET -j 8"
su $U -c "/usr/local/cargo/bin/cargo fmt --all -- --check"
su $U -c "/usr/local/cargo/bin/cargo clippy $BUILD_FLAGS $TARGET -j 8 -- -D clippy::all"
su $U -c "RUST_BACKTRACE=1 /usr/local/cargo/bin/cargo test -j 1 $TARGET"
su $U -c "/usr/local/cargo/bin/cargo doc"


GREEN='\033[1;32m'
NC='\033[0m'

echo
echo "    ${GREEN}Running system tests${NC}"

rm -rf target/path
if echo $BUILD_FLAGS | grep 'release' >/dev/null ; then
    ln -s "x86_64-unknown-linux-musl/release/" target/path
else
    ln -s "x86_64-unknown-linux-musl/debug/" target/path
fi
chown -h "$USER_ID":"$GROUP_ID" target/path

system-tests/test
